/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    Collections: typeof import('./src/components/LikedItems.vue')['default']
    HelloWorld: typeof import('./src/components/Images.vue')['default']
    Images: typeof import('./src/components/Images.vue')['default']
    LikedItems: typeof import('./src/components/LikedItems.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/Auth.vue')['default']
  }
}
